### ISSUE TITLE
Non-universal definition of specific humidity

### ISSUE THREAD

**Issue by MayeulDestouches** [ESCOMP/CCPPStandardNames#36]
Variable `specific_humidity` is defined in rule 5 of the [CCPP Standard Name Rules](https://github.com/ESCOMP/CCPPStandardNames/blob/main/StandardNamesRules.rst).

>5.  By default, mixing_ratio refers to mass mixing ratios. The long name should explicitly specify that it refers to the mass mixing ratio. Mass mixing ratios should contain information regarding with respect to what quantity they are defined, and options are wrt_dry_air, wrt_moist_air, or wrt_total_mass, where moist_air refers to dry air plus vapor and total_mass refers to dry air plus vapor and hydrometeors. **A special case exists in the case of mixing ratio of vapor: the standard name specific_humidity should be used instead of mixing_ratio_of_vapor_wrt_moist_air.**

This definition as an alias of `mixing_ratio_of_vapor_wrt_moist_air` is not universal. At the UK Met Office for instance, what we call specific humidity is `mixing_ratio_of_vapor_wrt_total_mass`. This definition is used consistently across all our code, from NWP to climate. The definition here, `_wrt_moist_air`, is used in the UFS/GFS physics (according to @climbfuji). 

There seems to be no agreement on what specific_humidity really means. I would have liked the definition to be changed to the Met Office's one, but a better and more acceptable solution would be to simply remove this ambiguous name in the CCPP standard.

`water_vapor_mixing_ratio_wrt_dry_air` is already a CCPP name, I propose to add `water_vapor_mixing_ratio_wrt_moist_air` and `water_vapor_mixing_ratio_wrt_total_mass` as a replacement for `specific_humidity`. 

Any comment welcome.

**Comment by MayeulDestouches** [comment]
Pinging @svahl991, @ligiabernardet.

**Comment by climbfuji** [comment]
I am in favor of making this change. CCPP after all is a model-independent effort and shouldn't give priority to one or another.

**Comment by PeterHjortLauritzen** [comment]
Thank you for bringing this issue up!

Agreed that specific humidity can be ambiguous as some models define moist air as dry air + water vapor (hence moist air only includes the gaseous components of air) whereas other models include condensates in moist air in addition to dry air+water vapor. If condensates are included then there is the question of which ones (which is model specific). 

A way to avoid these ambiguities (except which condensates are in moist air) could be:

water_vapor_mixing_ratio_wrt_dry_gas
water_vapor_mixing_ratio_wrt_moist_gas
water_vapor_mixing_ratio_wrt_moist_gas_and_condensates

ps. the same argument can be made for hydrostatic pressure (does the weight of the column incl. condensates or not?)

**Comment by MayeulDestouches** [comment]
Thanks @PeterHjortLauritzen for your comment. I think rule 5, quoted above, proposes a clear way to avoid this ambiguities:

> ... options are wrt_dry_air, wrt_moist_air, or wrt_total_mass, where moist_air refers to dry air plus vapor and total_mass refers to dry air plus vapor and hydrometeors. 

which gives the following options: 

water_vapor_mixing_ratio_wrt_dry_air
water_vapor_mixing_ratio_wrt_moist_air
water_vapor_mixing_ratio_wrt_total_mass

About which condensates are included in the total mass or not, I think there is no ambiguity within a given model. Each model includes all available information to approximate total mass as best as it can. If someone faces a special case where the ambiguity does need to be removed, further names could be added (for instance, water_vapor_mixing_ratio_wrt_moist_air_and_cloud_water). I think this may be beyond the scope of this issue though.

**Comment by PeterHjortLauritzen** [comment]
Your proposal probably avoids ambiguity except for water_vapor_mixing_ratio_wrt_moist_air. Different modeling groups define moist air differently. In the UK Met Office's Joy of U.M. documentation section 1.5 defines moist air as dry air + all phases of water. Whereas your definition only includes dry air and water vapor.

Link to documentation here: ftp://wxmaps.org/pub/kjin/UM/p015.pdf

I also find it a little inconsistent to use "_mass" in one of the definitions and no mention of mass in the other definitions.

That said, if there is consensus to use 

water_vapor_mixing_ratio_wrt_dry_air
water_vapor_mixing_ratio_wrt_moist_air
water_vapor_mixing_ratio_wrt_total_mass

then I won't drag out this discussion further ...

**Comment by gold2718** [comment]
> About which condensates are included in the total mass or not, I think there is no ambiguity within a given model

@MayeulDestouches, can you elaborate on this? Where is the model boundary? Can parameterizations coming via the CCPP make different assumptions?

**Comment by climbfuji** [comment]
FYI The UK MetOffice uses the CCPP standard names as part of the JEDI-UM model interfaces. They don't use it for the physics. (JEDI adopted the CCPP standard names to describe variables in the model interfaces.)

**Comment by MayeulDestouches** [comment]
### About `_wrt_moist_air`
> Different modeling groups define moist air differently. 

@PeterHjortLauritzen, I agree `moist_air` is ambiguous for someone who doesn't know rule 5. 

> A way to avoid these ambiguities (except which condensates are in moist air) could be:
>
> water_vapor_mixing_ratio_wrt_dry_gas
> water_vapor_mixing_ratio_wrt_moist_gas
> water_vapor_mixing_ratio_wrt_moist_gas_and_condensates

I agree this would be better names. However, the renaming would have a large impact, as there are already 36 CCPP standard names using `mixing_ratio_wrt_moist_air`. Current use of `dry_air` is also consistent with several other CCPP names such as `gas_constant_of_dry_air` or `air_pressure_of_dry_air`. This is why I believe keeping `air` is simpler than `gas`:

- `_wrt_dry_air`
- `_wrt_moist_air`

We should just make sure people are well aware of the definition in rule 5. 

Can people please comment on this? I'm happy to change my mind depending on general consensus.

### About `_wrt_total_mass`

I agree with @PeterHjortLauritzen  and @gold2718 that the prefix `_wrt_total_mass` is not perfect. It is currently not used in any CCPP standard names, nor in the CF Standard Names, so we can agree on something different. Several standard CCPP names use `condensed_water` and `cloud_condensed_water`. I propose to replace `_wrt_total_mass` in rule 5 by the alternative prefixes: 

- `_wrt_moist_air_and_condensed_water`
- `_wrt_moist_air_and_cloud_condensed_water`

I think this would also make it clearer that moist air does not include condensed water (for the CCPP standard).

**Comment by MayeulDestouches** [comment]
> @MayeulDestouches, can you elaborate on this? Where is the model boundary? Can parameterizations coming via the CCPP make different assumptions?

Maybe my understanding was a bit naive: if a global scale models has a cloud liquid water variable and a cloud ice variable but no rain, snow or graupel, it can only compute `total_mass` as dry air + humidity + cloud liquid water + cloud ice water. Now, for a convective-scale model with rain, snow and graupel, total mass would also include rain, snow and graupel. This makes different computations of total mass, but I thought this was okay as they could both be considered as different practical approximations of the same concept of total mass. 
@gold2718, I admit this would not work if different parts of the model need to interact and the one with the most accurate approximation needs to convert between both. I hope using the names proposed in my previous comment will solve this.

**Comment by PeterHjortLauritzen** [comment]
@MayeulDestouches: I agree that

_wrt_dry_air
_wrt_moist_air
_wrt_moist_air_and_condensed_water

would be a good compromise.

ps. I think "_wrt_moist_air_and_cloud_condensed_water" would be a bit confusing if a model has prognostic rain, graupel etc. since they are not necessarily part of a cloud ...

**Comment by MayeulDestouches** [comment]
@PeterHjortLauritzen, I proposed 
(1): `water_vapor_mixing_ratio_wrt_moist_air_and_cloud_condensed_water`
in addition to 
(2): `water_vapor_mixing_ratio_wrt_moist_air_and_condensed_water`
especially because (1) does not include precipitating hydrometeors (rain, graupel, snow etc), that's the point. 

So a model with precipitating hydrometeors could compute both (1) and (2), while a model with only cloud liquid water and cloud ice water can only use (1). 

This is supposed to (partly) answer the question of which condensates were included or not in the (soon deprecated) `total_mass`.
Does it make sense? Or would you just use `wrt_moist_air_and_condensed_water` regardless of which water condensates are actually considered for the computation?
