### ISSUE TITLE
Need to add definitons

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CCPPStandardNames#4]
Need to add definitions for:

- lagrangian_vertical  (flag)
- geopotential
- geopotential_at_interface
- physics_state_from_dynamics
- total_physics_tendency

**Comment by gold2718** [comment]
The dictionary is correct with `geopotential_height` and `geopotential_height_at_interface`.
Also, the flag standard name should be `lagrangian_vertical_coordinate`.
I do not think that `physics_state_from_dynamics` or `total_physics_tendency` should go in the dictionary, they specify internal CAM data structures and are not meant to be portable.
In summary, they only change I see from this list is to add `lagrangian_vertical_coordinate`.

**Comment by cacraigucar** [comment]
I thought we wanted geopotential and geopotential_height.  I will let Jesse do all the goepotential changes.  I've made them in several places which have not been committed and am now totally confused on which one is which and what the units are.

**Comment by gold2718** [comment]
I believe the dictionary entries for `geopotential_at_surface`, `geopotential_height`, and `geopotential_height_at_interface` are correct. @nusbaume, do you agree?

**Comment by nusbaume** [comment]
Yep, the current `geopotential_*` variables are all correct.  However if we need explicit `geopotential` variables (instead of `geopotential_height`) then we will need to add  new definitions, which should have the same units as `geopotential_at_surface`.

**Comment by cacraigucar** [comment]
Closed with #10
