### ISSUE TITLE
Want Github Action to ensure standard names are following character rules

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/CCPPStandardNames#42]
As described by the CF-conventions here:

http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html

standard names should start with a letter, and only contain lower-case letters, numbers, and underscores.  This rule should be enforceable in an automated fashion, and thus it would be good to have a Github Action for the dictionary that ensures that only standard names that follow this rule are allowed.

**Comment by mkavulich** [comment]
Resolved via #52
