### ISSUE TITLE
New standard names for land surface variables

### ISSUE THREAD

**Issue by SamanthaPullen** [ESCOMP/CCPPStandardNames#59]
I would like to add some variable names to the CCPP Standard Names for some land surface variables, in preparation for Met Office work on land surface DA with JEDI. The names I am planning to add are as follows:

1. `surface_snow_density`
2. `mass_content_of_water_in_top_soil_layer`
3. `volume_fraction_of_liquid_water_in_soil_at_wilting_point`
4. `volume_fraction_of_liquid_water_in_soil_at_critical_point`
5. `volume_fraction_of_liquid_water_in_soil_at_saturation`
6. `urban_area_fraction`
7. `land_ice_area_fraction`

I have used [CF Standard Names (cfconventions.org)](https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html) where possible, and where nothing suitable exists I have based the proposed CCPP name on the CCPP or CF name of a related or similar variable.

I think it would make sense to add a new sub-section for these surface variables  - any views on whether this is for all surface variables (i.e. land, sea, sea-ice), or just restricted to land surface?

I will open a PR for these additions and link it to this issue - this is just a heads-up of the planned additions

**Comment by SamanthaPullen** [comment]
Draft PR #60 opened to address this issue

**Comment by ss421** [comment]
On the `land_ice_area_fraction`, there is some related discussion in #57. Ive added some notes there.

**Comment by mkavulich** [comment]
Resolved by #60
