### ISSUE TITLE
Clarification regarding `_at_interface` suffix

### ISSUE THREAD

**Issue by svahl991** [ESCOMP/CCPPStandardNames#61]
I wanted to clarify the meaning of the `_at_interface` suffix. Rule #4 of the standard name rules states:

> By default (when not specified otherwise), variables are grid means or centers (defined by the host). If a variable is defined at a different physical location, a qualifier should be used to denote this. For example, for variables representing quantities at the interface between grid cells vertically, use at_interface.

So if a model has `n` grid cells vertically, then `<variable>` has `n` vertical levels. But how many vertical levels does `<variable>_at_interface` have? `n-1`, `n`, or `n+1`? Are both the model top and bottom (surface) of the model included in `<variable>_at_interface`? Neither? Or just one or the other? Which? 

I notice there are also naming suffixes for `at_top_of_atmosphere_model` and `at_surface_adjacent_layer`, so does that mean those locations are not included in `_at_interface`?

I ask because in my work on JEDI I think I have uncovered that different organizations see `<variable>_at_interface` differently, with one group seeing the surface as a separate layer that is not included in `_at_interface` (but they do include the model top). Another group appears to include both model top and surface in `_at_interface`.

**Comment by dudhia** [comment]
From my perspective the number of interface layers is n+1, surface and top
included. I would regard this as more common.

**Comment by nusbaume** [comment]
I agree with @dudhia, in that at least for the NCAR models the number of interface layers is `n+1`, including both the bottom and top.

Also the `at_top_of_atmsophere_model` and `at_surface_adjacent_layer` suffixes are usually reserved for 2-D quantities where it is unclear from the dimensions alone where they are located vertically.  However the 3-D equivalents of those variables could certainly be `_at_interface`.  Hopefully that makes sense?

**Comment by svahl991** [comment]
There seems to be agreement from most people I've heard from that `_at_interface` should have n+1 levels and include both the bottom (surface) and the top of the model. However, I recently met with some people from the Met Office and confirmed that the typical usage of `_at_interface` in their models does not include the surface and only has n levels. We thought maybe they will need to use a new suffix, something like `_at_interface_excluding_surface`. What do people think of that idea? Does anyone have other ideas? 

@MayeulDestouches @ss421

**Comment by MayeulDestouches** [comment]
Following an offline discussion with @ss421  and @svahl991, I plan to open a PR to clarify the rules on suffixes related to vertical grid information. This would include a new `_at_top_interfaces` suffix, as proposed in my previous comment. 

@dudhia, @nusbaume, @climbfuji, @gold2718, @mkavulich, would you be happy with this?

**Comment by nusbaume** [comment]
@MayeulDestouches That plan sounds good to me.  Thanks for the heads up!

**Comment by MayeulDestouches** [comment]
I close this issue, as it has been solved by #65.
