### ISSUE TITLE
Use of plural for `_in_atmosphere_layer`

### ISSUE THREAD

**Issue by MayeulDestouches** [ESCOMP/CCPPStandardNames#67]
As noted in https://github.com/ESCOMP/CCPPStandardNames/pull/65#issuecomment-2037581547 and the discussion that followed, there may be an inconsistency between the vertical staggering suffixes (e.g., `_at_interfaces`) and the `_in_atmosphere_layer` suffix. 
The latter is typically added to a 2D variable to specify that it is defined for each model level, thus making it a 3D variable. 

Should we rename `in_atmosphere_layer` into `in_atmosphere_layers`, to make the use of plural consistent?

**Comment by MayeulDestouches** [comment]
Tagging @nusbaume as he first raised the issue, and @gthompsnJCSDA as he once told me the `_in_atmosphere_layer` suffix was not clear and as he might have better suggestions.

**Comment by mkavulich** [comment]
It appears that, unlike the previous interface vs. interfaces discussion, this does have precedence in the CF conventions (https://cfconventions.org/Data/cf-standard-names/84/build/cf-standard-name-table.html) as "`_in_atmosphere_layer`" (singular). So I wouldn't recommend we diverge from that existing standard unless there is a very good reason.

**Comment by nusbaume** [comment]
Thanks for checking the CF conventions @mkavulich!  Given this new info I agree that we should probably keep `_in_atmosphere_layer` singular.  This will mean that it has a slightly different grammar than `_at_interfaces`, but in the end I personally think that's ok if it means more closely matching the CF conventions for atmosphere layers, while at the same time preventing any confusion when it comes to vertical interfaces (which benefit from being plural).

I'll leave this issue open for a couple more weeks in case  anyone else has any thoughts or opinions, but if not then I'll go ahead and close it after the next CCPP-framework meeting.  Thanks!

**Comment by gthompsnJCSDA** [comment]
I am utterly confused here.  I thought this issue closed out by @climbfuji a couple weeks ago.  It was a back and forth with regard to plural versus singular and it seemed it already moved into plural.

**Comment by MayeulDestouches** [comment]
@gthompsnJCSDA, I think what you're referring to is PR #65 where this discussion was initiated. It was decided there that plural should be used for vertical stagger information (e.g., `_at_top_interfaces`).
Note that the present issue is not about that suffix, it is about the `_in_atmosphere_layer` one.

**Comment by nusbaume** [comment]
Given that we decided above to leave the `_in_atmospher_layer` prefix as-is to better match the CF standard, and that there hasn't been any new discussion on this topic for the past few weeks, I will go ahead and close this as a "won't fix".  Thanks!
