### ISSUE TITLE
Implement python3 compatibiliy

### ISSUE THREAD

**Issue by gold2718** [ESCOMP/CCPPStandardNames#7]
Python 2 is EOL, get with the program.

**Comment by gold2718** [comment]
@davegill, I tried following the README instructions with python 3.6.10 and it ran with no errors. Please report the python version and error.

**Comment by davegill** [comment]
@gold2718 
Steve,
I can't replicate the error on any machine I would have been testing this on. I have tried several python 2.7.* and python 3.6.* and no troubles at all.

Dang gamma rays. 

We are apparently good to go AS-IS. Mea culpa.

**Comment by ligiabernardet** [comment]
I am closing this issue since it turns out the script is working with Python 3.
