### ISSUE TITLE
Question about correct skin_temperature CCPP name

### ISSUE THREAD

**Issue by svahl991** [ESCOMP/CCPPStandardNames#83]
During the JCSDA JEDI variable naming sprint, we added variables to JEDI called:
```
skin_temperature_at_surface_where_sea
skin_temperature_at_surface_where_land
skin_temperature_at_surface_where_ice
skin_temperature_at_surface_where_snow
```
I was going to submit a PR to add these names to CCPP, but I do not see that CCPP names ever use the `_where_` preposition. I see `_in_` and I see `_over_`. Sometimes both in the same name, as in `temperature_in_surface_snow_at_surface_adjacent_layer_over_ice`.

So I'm not sure what the "correct" CCPP names should be for the four variables we added. _e.g._
`skin_temperature_in_surface_sea`?
`skin_temperature_at_surface_in_sea`?

**Comment by svahl991** [comment]
Tagging @travissluka @rtodling @mikecooke77 @fmahebert

**Comment by gold2718** [comment]
Is there a problem with using `_over_` here? Different meaning?

**Comment by travissluka** [comment]
> Is there a problem with using `_over_` here? Different meaning?

Yes, different meaning. With `..._where_sea` for example we're looking for the temperature _within_ the ocean, not the temperature of the atmosphere _above_ the ocean.

**Comment by climbfuji** [comment]
`_over_` does not mean `above`. Over stands for the type of the area, for example in the context of a fractional landmask where a grid cell contains areas that are over ocean and areas over land. The `over` stands for exactly the same thing that you are trying to describe with `where`.

**Comment by svahl991** [comment]
> `_over_` does not mean `above`. Over stands for the type of the area, for example in the context of a fractional landmask where a grid cell contains areas that are over ocean and areas over land. The `over` stands for exactly the same thing that you are trying to describe with `where`.

Since there has been no more discussion on this I'll submit the PR with `over`, since that is the CCPP standard, and given @climbfuji 's explanation of it's meaning. Although I will say that if that is the intended meaning, then `where` seems more intuitive to me, and doesn't hold the same possibility being misunderstood as meaning "above", as we did.
